name: Build Odigos Images

on:
  workflow_call:
    inputs:
      tag:
        description: 'The image tag to build'
        required: true
        type: string
      push:
        required: false
        default: false
        type: boolean
      save:
        description: 'Optionaly save the images to odigos-images.tar to be used in a future job'
        required: false
        default: false
        type: boolean

jobs:
    build-image:
      strategy:
        matrix:
          include:
            - service: autoscaler
              runner: ubuntu-latest
            - service: scheduler
              runner: ubuntu-latest
            - service: instrumentor
              runner: ubuntu-latest
            - service: collector
              runner: large-runner
            - service: odiglet
              runner: ubuntu-latest
            - service: ui
              runner: ubuntu-latest
      runs-on: ${{ matrix.runner }}
      steps:
          - name: Print Inputs
            run: |
              echo "Tag: ${{ inputs.tag }}"
              echo "Push: ${{ inputs.push }}"
              echo "Save: ${{ inputs.save }}"
          - name: Checkout
            uses: actions/checkout@v4
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build and Push Docker Image for ${{ matrix.service }}
            uses: docker/build-push-action@v6
            with:
              push: ${{ inputs.push == 'true' }}
              tags: keyval/odigos-${{ matrix.service }}:${{ inputs.tag }}
              build-args: |
                  SERVICE_NAME=${{ matrix.service }}
                  ODIGOS_VERSION=${{ inputs.tag }}
              platforms: linux/amd64,linux/arm64
              file: >-
                  ${{
                  (matrix.service == 'odiglet' && 'odiglet/Dockerfile') ||
                  (matrix.service == 'collector' && 'collector/Dockerfile') ||
                  (matrix.service == 'ui' && 'frontend/Dockerfile') ||
                  'Dockerfile'
                  }}
              context: >-
                  ${{
                  (matrix.service == 'collector' && 'collector') ||
                  '.'
                  }}
              cache-from: type=gha
              cache-to: type=gha,mode=max
          - name: Save Odigos images to tar
            if: always() && ${{ inputs.save == 'true' }}
            run: docker save -o odigos-images.tar $(docker images --format "{{.Repository}}:{{.Tag}}" | grep "odigos")
          - name: Upload Odigos Images
            if: always() && ${{ inputs.save == 'true' }}
            uses: actions/upload-artifact@v3
            with:
              name: odigos-images
              path: odigos-images.tar